FROM ubuntu:24.04

LABEL maintainer="ozabramovs@gmail.com"

ENV DEBIAN_FRONTEND=noninteractive

ARG WINE_VERSION=winehq-devel
ARG PYTHON_VERSION=3.13.0
ARG PYINSTALLER_VERSION=6.11.1

# Add 32-bit architecture for Wine
RUN set -x \
    && dpkg --add-architecture i386 \
    && apt update -qy \
    && apt install --no-install-recommends -qfy \
        apt-transport-https \
        software-properties-common \
        wget \
        gpg-agent \
        rename \
        winehq-devel \
        wine64 \
        wine32 \
        winbind \
        cabextract \
    && mkdir -pm755 /etc/apt/keyrings \
    && wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key \
    && wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/noble/winehq-noble.sources \
    && apt update -qy \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

# Install winetricks and configure Wine
RUN wget -nv https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks \
    && chmod +x winetricks \
    && mv winetricks /usr/local/bin

# Set Wine environment variables
ENV WINEARCH=win64
ENV WINEDEBUG=fixme-all
ENV WINEPREFIX=/wine
ENV PYPI_URL=https://pypi.python.org/
ENV PYPI_INDEX_URL=https://pypi.python.org/simple

# Install Python in Wine
RUN set -x \
    && winetricks win10 \
    && for msifile in `echo core dev exe lib path pip tcltk`; do \
        wget -nv "https://www.python.org/ftp/python/$PYTHON_VERSION/amd64/${msifile}.msi"; \
        wine msiexec /i "${msifile}.msi" /qb TARGETDIR=C:/Python3; \
        rm ${msifile}.msi; \
    done \
    && cd /wine/drive_c/Python3 \
    && echo 'wine '\''C:\Python3\python.exe'\'' "$@"' > /usr/bin/python \
    && echo 'wine '\''C:\Python3\Scripts\easy_install.exe'\'' "$@"' > /usr/bin/easy_install \
    && echo 'wine '\''C:\Python3\Scripts\pip.exe'\'' "$@"' > /usr/bin/pip \
    && echo 'wine '\''C:\Python3\Scripts\pyinstaller.exe'\'' "$@"' > /usr/bin/pyinstaller \
    && echo 'wine '\''C:\Python3\Scripts\pyupdater.exe'\'' "$@"' > /usr/bin/pyupdater \
    && chmod +x /usr/bin/python /usr/bin/easy_install /usr/bin/pip /usr/bin/pyinstaller /usr/bin/pyupdater \
    && (pip install -U pip || true) \
    && rm -rf /tmp/.wine-*

# Install the Visual C++ Redistributable DLLs for Wine
RUN set -x \
    && wget -P "$W_TMP" https://download.visualstudio.microsoft.com/download/pr/11100230/15ccb3f02745c7b206ad10373cbca89b/VC_redist.x64.exe \
    && cabextract -q --directory="$W_TMP" "$W_TMP"/VC_redist.x64.exe \
    && cabextract -q --directory="$W_TMP" "$W_TMP/a10" \
    && cabextract -q --directory="$W_TMP" "$W_TMP/a11" \
    && cd "$W_TMP" \
    && rename 's/_/\-/g' *.dll \
    && cp "$W_TMP"/*.dll "$W_SYSTEM64_DLLS"/

# Install PyInstaller
RUN /usr/bin/pip install --no-cache-dir pyinstaller==$PYINSTALLER_VERSION

# Create src folder and mount it
RUN mkdir /src/ && ln -s /src /wine/drive_c/src
VOLUME /src/
WORKDIR /wine/drive_c/src/

# Setup tmp directory
RUN mkdir -p /wine/drive_c/tmp

# Copy entrypoint script
COPY entrypoint-windows.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
